apiVersion: v1
kind: Service
metadata:
  name: bug-blaster-server1-service
  labels:
    app: myapp
spec:
  selector:
    app: bug-blaster-server1
  ports:
    - port: 3005
      targetPort: 3100
  type: LoadBalancer